baseURL = "http://example.com/"
languageCode = "en-us"
title = "Roxanne DSIntro Blog"
theme = "minimal"

[params]
    author = "Roxanne Stockard"
    description = "R tutorial for websites"
    githubUsername = "rstockard"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:rstock01@lakers.mercyhurst.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rstockard"
    name = "github"
    weight = 2


